from .base_exception import BaseNotProvidedError